#ifndef GAME_STORY_TABLE_H
#define GAME_STORY_TABLE_H
#include "types.h"
enum STORY_TYPE {
	STORY_TYPE_SONIC   = 0,
	STORY_TYPE_DARK    = 1,
	STORY_TYPE_ROSES   = 2,
	STORY_TYPE_CHAOTIX = 3,
	STORY_TYPE_LAST    = 4,
	STORY_TYPE_MAX     = 5
};
enum SEQ_TYPE { SEQ_STAGE = 0, SEQ_MOVIE = 1, SEQ_STAFFROLL = 2, SEQ_MAX = 3 };
enum SEQ_STAUS {
	SEQ_STAUS_CONTINUE = 0,
	SEQ_STAUS_CLEAR    = 1,
	SEQ_STAUS_NOHIT    = 2,
	SEQ_STAUS_MAX      = 3
};
enum ACTIONSTAGE_NUMBER {
	ACTIONSTAGE_END             = 0,
	ACTIONSTAGE_PRACTICE_00     = 1,
	ACTIONSTAGE_OCEAN_01        = 2,
	ACTIONSTAGE_OCEAN_02        = 3,
	ACTIONSTAGE_HOTPLANT_03     = 4,
	ACTIONSTAGE_HOTPLANT_04     = 5,
	ACTIONSTAGE_CASINO_05       = 6,
	ACTIONSTAGE_CASINO_06       = 7,
	ACTIONSTAGE_TRAIN_07        = 8,
	ACTIONSTAGE_TRAIN_08        = 9,
	ACTIONSTAGE_BIGPLANT_09     = 10,
	ACTIONSTAGE_BIGPLANT_10     = 11,
	ACTIONSTAGE_GHOST_11        = 12,
	ACTIONSTAGE_GHOST_12        = 13,
	ACTIONSTAGE_SKYEGG_13       = 14,
	ACTIONSTAGE_SKYEGG2_14      = 15,
	BOSSSTAGE_EGGHAWK_20        = 16,
	BOSSSTAGE_VSCHARA1ST_21     = 17,
	BOSSSTAGE_ZAKORUSH_22       = 18,
	BOSSSTAGE_EGGALBATROSS_23   = 19,
	BOSSSTAGE_TEAMBATTLE2_24    = 20,
	BOSSSTAGE_ZAKORUSH_25       = 21,
	BOSSSTAGE_KINGPAWN_26       = 22,
	BOSSSTAGE_LASTBOSS1ST_27    = 23,
	BOSSSTAGE_LASTBOSS2ND_28    = 24,
	TUTORIALSTAGE_29            = 25,
	BOUNUSSTAGE_31              = 26,
	BOUNUSSTAGE_32              = 27,
	BOUNUSSTAGE_33              = 28,
	SPECIALSTAGE_40             = 29,
	SPECIALSTAGE_41             = 30,
	SPECIALSTAGE_42             = 31,
	SPECIALSTAGE_43             = 32,
	SPECIALSTAGE_44             = 33,
	SPECIALSTAGE_45             = 34,
	SPECIALSTAGE_46             = 35,
	ACTIONSTAGE_TRAIN_50        = 36,
	BATTLE2P_SEASIDEHILL_60     = 37,
	BATTLE2P_GRANDMETROPOLIS_61 = 38,
	BATTLE2P_BINGOHIGHWAY_62    = 39,
	BATTLE2P_CITYTOP_63         = 40,
	BATTLE2P_CASINORING_64      = 41,
	BATTLE2P_TURTLESHELL_65     = 42,
	BATTLE2P_EGGTREAT_66        = 43,
	BATTLE2P_PINBALLMATCH_67    = 44,
	BATTLE2P_HOTELEVATOR_68     = 45,
	BATTLE2P_ROADROCK_69        = 46,
	BATTLE2P_MADEXPRESS_70      = 47,
	BATTLE2P_TERRORHALL_71      = 48,
	BATTLE2P_RAILCANYON_72      = 49,
	BATTLE2P_FROGFOREST_73      = 50,
	BATTLE2P_EGGFLEET_74        = 51,
	BOUNUSSTAGE_80              = 52,
	BOUNUSSTAGE_81              = 53,
	BOUNUSSTAGE_82              = 54,
	BOUNUSSTAGE_83              = 55,
	BOUNUSSTAGE_84              = 56,
	BOUNUSSTAGE_85              = 57,
	BOUNUSSTAGE_86              = 58,
	BOUNUSSTAGE_87              = 59,
	BOUNUSSTAGE_88              = 60,
	BOUNUSSTAGE_89              = 61,
	MAX_ACTION_STAGE            = 62
};
struct STORY_TABLE {
	s32 seqFlag;
	SEQ_TYPE type;
	s32 data;
};
struct STORY_INFO {
	STORY_TABLE* storyTable;
	s32 ele;
};
class STORYMANAGE
{
public:
	STORY_TYPE currentStory;
	s32 seqStep;
	static STORY_INFO storyInfo[5];
	s32 MustExit(ACTIONSTAGE_NUMBER);
	s32 SetBonusStage(ACTIONSTAGE_NUMBER);
	s32 WarpSeqStep(ACTIONSTAGE_NUMBER);
	s32 SetActionStageConnect(s32);
	s32 CurrentMovieNumber();
	SEQ_TYPE CheckCurrentSeqType();
	SEQ_STAUS StepMovieSeq();
	SEQ_STAUS StepStageSeq(ACTIONSTAGE_NUMBER);
	s32 CheckStoryProgress(STORY_TYPE, s32);
	s32 SetStory(STORY_TYPE);
	s32 getCurrentSeq(STORY_TYPE);
};
extern STORYMANAGE StoryManage;
#endif
